# 빅데이터 전처리 및 시각화

## NumPy

### 패키지: 설치해서 사용해야 한다

In [1]:
 import numpy

In [3]:
A=numpy.random.randn(3,2)
A.shape, A.dtype #64비트 실수

((3, 2), dtype('float64'))

In [5]:
 import numpy as np

In [6]:
A=np.random.randn(3,2)
A.shape, A.dtype #64비트 실수

((3, 2), dtype('float64'))

In [16]:
ls1 = [1,2,4,4]
ls2 = [33,25,74,78]
vec_x = np.array((4,2,5,4,3))
mat_A=np.array([ls1,ls2])
print(mat_A) # 콤마로 분리된 행렬 구조
print(vec_x.shape, vec_x.dtype)
print(mat_A.shape, mat_A.dtype)
print(np.asarray(ls1))
vec_y=np.asarray(ls2)
print(vec_y,vec_y.shape,vec_y.dtype)
mat_B=np.asarray(mat_A)
print(mat_B,mat_B.shape,mat_B.dtype)
print(id(mat_A),id(mat_B)) # A를 asarray한게 B, ID값 같다 = 
# A가 이미 ARRAY이면 기존의 ARRAY를 그대로 복사해서 B를 만든다

[[ 1  2  4  4]
 [33 25 74 78]]
(5,) int32
(2, 4) int32
[1 2 4 4]
[33 25 74 78] (4,) int32
[[ 1  2  4  4]
 [33 25 74 78]] (2, 4) int32
2297755737024 2297755737024


In [18]:
ls1=[1,2,4,4]
ls2=[33,25,74,78]
vec_x=np.arange(1,10,2)
vec_x

array([1, 3, 5, 7, 9])

In [25]:
print(np.zeros(4))
print(np.zeros((4,5)))
print(np.eye(5))
print(np.identity(5))

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [27]:
ls1=[1,2,4,4]
ls2=[33,3,25,362,74,76,78,19]
vec_x=np.array(ls1,dtype=np.string_)
print(vec_x,vec_x.dtype)

[b'1' b'2' b'4' b'4'] |S1


In [28]:
ls1=[1,2,4,4]
ls2=[33,3,25,362,74,76,78,19]
vec_x=np.array(ls1)
vec_x.astype(np.float64)
print(vec_x,vec_x.dtype)

[1 2 4 4] int32


In [37]:
ls1=[1,2,4,4]
ls2=[33,3,25,362,74,76,78,19]
mat=np.array([ls1,ls2])
print(mat.dtype)
mat=mat.astype(np.int16)
print(mat.dtype)

object


ValueError: setting an array element with a sequence.

In [43]:
ls1=[1,2,4,4]
ls2=[33.3,25.362,74.76,78.19]
vec=np.array(ls1)
print(vec, 2*vec)
mat=np.array([ls1,ls2])
print(mat)
print(mat,2*mat, mat+10)
vec1=np.array([ls1])
vec2=np.array([ls2])
print(vec1*vec2)
mat1=np.array([ls1,ls2])
mat2=np.array([[2,5,1,2],[3,1,4,7]])
print(mat1*mat2) # mat1[0]*mat2[0] mat1[1]*mat2[1] ..... 
# 우리가 흔히 아는 행렬곱이 아니라, 같은 위치의 원소끼리 곱해줌(cartesian)

[1 2 4 4] [2 4 8 8]
[[ 1.     2.     4.     4.   ]
 [33.3   25.362 74.76  78.19 ]]
[[ 1.     2.     4.     4.   ]
 [33.3   25.362 74.76  78.19 ]] [[  2.      4.      8.      8.   ]
 [ 66.6    50.724 149.52  156.38 ]] [[11.    12.    14.    14.   ]
 [43.3   35.362 84.76  88.19 ]]
[[ 33.3    50.724 299.04  312.76 ]]
[[  2.     10.      4.      8.   ]
 [ 99.9    25.362 299.04  547.33 ]]


In [54]:
ls1=[1,2,4,4,2,4,4,5,1,2]
vec=np.array(ls1) 
print(ls1[2],vec[2])


print(ls1[2], "\t", vec[2])
print(ls1[1:3], "\t", vec[1:3])  # 인덱싱이나 슬라이싱을 하는것 자체로는
#리스트랑 벡터 똑같다

ls1[3:6]=[999]; vec[3:6]=999
print(ls1, "\t", vec) # 이 때 리스트와 벡터 달라진다

4 4
4 	 4
[2, 4] 	 [2 4]
[1, 2, 4, 999, 4, 5, 1, 2] 	 [  1   2   4 999 999 999   4   5   1   2]


###  sub vector는 vector의 일부분을 그대로 갖다쓴다
### (가져다가 새로운 sub vector를 만드는게 아니라)
### 따라서 sub vector 바꾸면 원래 vector도 바뀜

In [57]:
ls1=[1,2,4,7,2,9,5,4,2]
ls2=[33.3,25.362,74.76, 78.19]
vec=np.array(ls1)
sub_vec1=vec[2:6]
print(vec, "\t", sub_vec1)
sub_vec1[2]=9999
print(vec,"\t", sub_vec1)# sub vector는 vector의 일부분을 그대로 갖다쓴다
# 가져다가 새로운 sub vector를 만드는게 아니라
# 따라서 sub vector 바꾸면 원래 vector도 바뀜

[1 2 4 7 2 9 5 4 2] 	 [4 7 2 9]
[   1    2    4    7 9999    9    5    4    2] 	 [   4    7 9999    9]


### 그럼 공유되는게 싫다 -> copy 사용

In [66]:
ls1=[1,2,4,7,2,9,5,4,2]
ls2=[33.3,25.362,74.76, 78.19]
vec=np.array(ls1)
sub_vec1=vec[2:6]
sub_vec2=vec[2:6].copy()
print(vec, "\t", sub_vec1)
sub_vec2[2]=9999
print(vec,"\t", sub_vec2, sub_vec1)
# copy 사용해서 따로 만들었으므로 sub vector를 바꿔도 원본은 안바뀜

[1 2 4 7 2 9 5 4 2] 	 [4 7 2 9]
[1 2 4 7 2 9 5 4 2] 	 [   4    7 9999    9] [4 7 2 9]


### 2차원 이상의 배열은 차원의 인덱스를 사용

In [72]:
ls1=[1,2,4,7,2,9,5,4,3]
ls2=[33.3,25.362,74.76, 78.19, 34.6, 43.6, 90.2, 57.3, 25.6]
ls3=[10,20,40,20,60,30,20,10,80]
A=np.array([ls1,ls2,ls3])
print(A) #3개 행의 행렬 구조
print(A[0]) # 하나만 인덱싱하면 첫 번째 행 (0) 으로 인식한다
print(A[1,5])
print(A[1][5])
print(A[:2,2:5]) #부분행렬 추출 하는것처럼 추출
print(A[:2][2:5])
print(A[:2][:,2:5]) # 콜론을 넣어야 같아짐; A[a:b,c:d] = A[a:b][:,c:d]

[[ 1.     2.     4.     7.     2.     9.     5.     4.     3.   ]
 [33.3   25.362 74.76  78.19  34.6   43.6   90.2   57.3   25.6  ]
 [10.    20.    40.    20.    60.    30.    20.    10.    80.   ]]
[1. 2. 4. 7. 2. 9. 5. 4. 3.]
43.6
43.6
[[ 4.    7.    2.  ]
 [74.76 78.19 34.6 ]]
[]
[[ 4.    7.    2.  ]
 [74.76 78.19 34.6 ]]


### 3차원 행렬 만들기

In [78]:
ls11=[1,2,4,3]; ls12=[1,2,4,1]; ls13=[5,2,4,2]
ls21=[2,4,1,4]; ls22=[2,4,1,4]; ls23=[3,5,4,5]
arr3d=np.array([[ls11,ls12,ls13], [ls21,ls22,ls23]])
print(arr3d)
print(arr3d[0,1,3]) # 인덱스: 층, 행, 렬
print(arr3d[0][1,3]) # 이렇게 층 먼저 추출해도 똑같음
print(arr3d[0], "\n", arr3d[0,:2,:3]) # 슬라이스로 3차원 배열에서 추출할 수 있음

[[[1 2 4 3]
  [1 2 4 1]
  [5 2 4 2]]

 [[2 4 1 4]
  [2 4 1 4]
  [3 5 4 5]]]
1
1
[[1 2 4 3]
 [1 2 4 1]
 [5 2 4 2]] 
 [[1 2 4]
 [1 2 4]]


In [80]:
ls11=[1,2,4,3]; ls12=[1,2,4,1]; ls13=[5,2,4,2]
ls21=[2,4,1,4]; ls22=[2,4,1,4]; ls23=[3,5,4,5]
arr3d=np.array([[ls11,ls12,ls13], [ls21,ls22,ls23]])
sub_arr1=arr3d[:2,1]
sub_arr2=arr3d[:2,1].copy()
print(arr3d,"\n", sub_arr1, "\n\n\n", sub_arr2)

[[[1 2 4 3]
  [1 2 4 1]
  [5 2 4 2]]

 [[2 4 1 4]
  [2 4 1 4]
  [3 5 4 5]]] 
 [[1 2 4 1]
 [2 4 1 4]] 


 [[1 2 4 1]
 [2 4 1 4]]


In [81]:
ls11=[1,2,4,3]; ls12=[1,2,4,1]; ls13=[5,2,4,2]
ls21=[2,4,1,4]; ls22=[2,4,1,4]; ls23=[3,5,4,5]
arr3d=np.array([[ls11,ls12,ls13], [ls21,ls22,ls23]])
sub_arr1=arr3d[:2,1]
sub_arr2=arr3d[:2,1].copy()
arr3d[1,1,2]=9999
print(arr3d,"\n", sub_arr1, "\n\n\n", sub_arr2)

[[[   1    2    4    3]
  [   1    2    4    1]
  [   5    2    4    2]]

 [[   2    4    1    4]
  [   2    4 9999    4]
  [   3    5    4    5]]] 
 [[   1    2    4    1]
 [   2    4 9999    4]] 


 [[1 2 4 1]
 [2 4 1 4]]


In [ ]:
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
mat1=np.array([ls11,ls12,ls13])
print(mat1[1], "\t", mat1[[False,True,False]]) # 후자도 1행만 뽑는 것
print(mat1[1], "\t", mat1[mat1>=10])
print(mat1[1], "\t", mat1[mat1>=20])
print(mat1[1], "\t", mat1[mat1>=30])
print(mat1>=20)

### 논리값을 통한 인덱싱

In [97]:
gender=np.array(["남", "여", "여", "남", "남", "여"])
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[3,2,6,7]; ls22=[103,403,202,601]; ls23=[124,142,115,114]
mat=np.array([ls11, ls12, ls13, ls21, ls22, ls23])
print(gender,"\n", mat)
result=gender=="남"
print(result)
male=mat[result]
female=mat[~result]
print("\n\n",male)
print("\n\n",female)

['남' '여' '여' '남' '남' '여'] 
 [[  1   2   5   3]
 [ 10  40  20  60]
 [  4   2   5   4]
 [  3   2   6   7]
 [103 403 202 601]
 [124 142 115 114]]
[ True False False  True  True False]


 [[  1   2   5   3]
 [  3   2   6   7]
 [103 403 202 601]]


 [[ 10  40  20  60]
 [  4   2   5   4]
 [124 142 115 114]]


### 논리값을 통한 인덱싱 응용

In [102]:
gender=np.array(["남", "여", "여", "남", "남", "여"])
ls11=[1,2,5,3]; ls12=[10,40,20,60]; ls13=[4,2,5,4]
ls21=[3,2,6,7]; ls22=[103,403,202,601]; ls23=[124,142,115,114]
mat=np.array([ls11, ls12, ls13, ls21, ls22, ls23])
print(gender,"\n", mat)
print(mat<10)
mat[mat<10]*10
mat[mat<10]=0
print(mat)

['남' '여' '여' '남' '남' '여'] 
 [[  1   2   5   3]
 [ 10  40  20  60]
 [  4   2   5   4]
 [  3   2   6   7]
 [103 403 202 601]
 [124 142 115 114]]
[[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]
[[  0   0   0   0]
 [ 10  40  20  60]
 [  0   0   0   0]
 [  0   0   0   0]
 [103 403 202 601]
 [124 142 115 114]]


### 팬시인덱싱 : 원하는 순서대로 나열하는 것

#### 주의할 것: 인덱싱 방식마다 뽑히는 법 다르다 (밑 참고)

In [118]:
ex=np.random.randn(7,5)
print(ex)
print("\n\n\n")
print(ex[[5,0,2], [3,1,4]])
print("\n\n\n")
print(ex[5,3])
print("\n\n\n")
print(ex[[5,0,2]][:,[3,1,4]]) # 약간 중첩된 for loop같은 느낌

#print(ex[[(5,4)],[(0,1)],[(2,4)]])

[[ 0.12049345 -0.15318818  0.73054055  0.14491629  0.52048708]
 [ 0.72394495 -0.12518344  0.34487564  0.51668782 -0.68361283]
 [-0.41264822  1.19067709  0.87615947 -0.27378301  0.67708873]
 [ 0.92352707  2.1059901  -0.92587231  0.03429619  1.63479643]
 [-0.25406256  1.42282732  0.39824619 -0.50645309  0.4143372 ]
 [-2.17186825 -0.0053124  -1.350677    0.2267292  -0.97616921]
 [ 0.1021801   0.14021341  0.62271846  0.76162038  1.4758564 ]]




[ 0.2267292  -0.15318818  0.67708873]




0.22672919902307523




[[ 0.2267292  -0.0053124  -0.97616921]
 [ 0.14491629 -0.15318818  0.52048708]
 [-0.27378301  1.19067709  0.67708873]]


### 배열의 전치와 축 바꾸기

In [125]:
ex=np.arange(24).reshape(2,4,3)
print(ex."\n\n", ex.transpose(2,0,1))

SyntaxError: invalid syntax (<ipython-input-125-838b4825c28e>, line 2)

## 범용 함수

In [128]:
np.array([1,4,2,np.inf,np.nan])

array([ 1.,  4.,  2., inf, nan])

In [135]:
A=np.arange(21).reshape(3,7)
B=np.random.randn(3,7)
print(A,"\n",B)
print("\n\n\n\n")
print(abs(B))
print(np.sign(B))
print(np.isfinite(B))

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] 
 [[-0.48500243 -0.26489519 -0.2258051   0.31466558  1.28082044 -1.25365766
  -1.17474742]
 [-0.29680804 -0.22189405 -0.23584172  0.55272019 -0.30887951 -1.27853221
   1.22894315]
 [ 1.72004115  0.26551314  0.58387034 -0.90675126  1.04420812 -0.87253031
   0.08909719]]





[[0.48500243 0.26489519 0.2258051  0.31466558 1.28082044 1.25365766
  1.17474742]
 [0.29680804 0.22189405 0.23584172 0.55272019 0.30887951 1.27853221
  1.22894315]
 [1.72004115 0.26551314 0.58387034 0.90675126 1.04420812 0.87253031
  0.08909719]]
[[-1. -1. -1.  1.  1. -1. -1.]
 [-1. -1. -1.  1. -1. -1.  1.]
 [ 1.  1.  1. -1.  1. -1.  1.]]
[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


## 배열을 사용한 데이터 처리

In [140]:
xarr=np.array([2,6,3,3,5])
yarr=np.array([3,5,2,5,6])
zarr=np.array(["서울", "경기", "서울", "인천", "경기"])
print(list(zip(xarr,yarr,zarr)))
result=[(x if z=="서울" else y) for x,y,z in zip(xarr,yarr,zarr)]
print(result)

[(2, 3, '서울'), (6, 5, '경기'), (3, 2, '서울'), (3, 5, '인천'), (5, 6, '경기')]
[2, 5, 3, 5, 6]


In [149]:
arr1=np.arange(21).reshape(7,3)
arr2=np.arange(21).reshape(7,3)*2
result=np.where(arr1>5,arr1,arr2)
print(arr1, "\n", arr2, "\n\n\n",result)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]] 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]
 [36 38 40]] 


 [[ 0  2  4]
 [ 6  8 10]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


### 통계 메소드 or 함수

#### 메소드

In [150]:
A=np.array([2,5,3,6,7,33])
B=np.array([3,6,4,6,7])
print(A.mean(), B.mean())

9.333333333333334 5.2


#### or

#### 함수

In [151]:
print(np.mean(A), np.mean(B))

9.333333333333334 5.2


In [159]:
A=np.array([[2,5,4], [3,5,1], [3,4,5]])
B=np.array([2,5,4,3,5,1,3,4,5])
print(A.mean()) # 특별히 명시하지 않으면 전체 원소에서 평균 구해줌
print(B.mean())
print(A.mean(axis=0), np.mean(A,axis=1)) # 열평균과 행평균
print(A.std(axis=0, ddof=1), np.std(A,axis=1, ddof=1)) # 열 표준편차와 행 표준편차

3.5555555555555554
3.5555555555555554
[2.66666667 4.66666667 3.33333333] [3.66666667 3.         4.        ]
[0.57735027 0.57735027 2.081666  ] [1.52752523 2.         1.        ]


### 논리값 배열을 위한 메소드
### 두개 이상의 논리값

In [161]:
B=np.array([2,5,3,5,3,2,4,3,2,1])
print(B.dtype) # 배열이다
print("\n", B>=5)
print("\n", (B>=5).mean()) # 비율값 (sum()=개수)

int32

 [False  True False  True False False False False False False]

 0.2


### 정렬

In [173]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
#print(sort(A), sort(B)) # 메소드 쓰면 돌려주는 값 없다 (None)
A.sort()
B.sort()
print(A,B)
A.sort(axis=0)
A

[[ 2  3  5]
 [ 6  7 33]
 [ 2  4  7]
 [ 4  7  9]] [ 2  2  3  4  4  5  6  7  7  7  9 33]


array([[ 2,  3,  5],
       [ 2,  4,  7],
       [ 4,  7,  9],
       [ 6,  7, 33]])

### 배열의 파일 입출력

In [177]:
A=np.array([[2,5,3],[6,7,33],[4,2,7],[7,9,4]])
B=np.array([2,5,3,6,7,33,4,2,7,7,9,4])
print(A,"\n\n",B)
np.save("C:/Users/Affinity/Desktop/Python_Data/arr_AB.npy",A2d=A, B1d=B)

[[ 2  5  3]
 [ 6  7 33]
 [ 4  2  7]
 [ 7  9  4]] 

 [ 2  5  3  6  7 33  4  2  7  7  9  4]


In [179]:
npy_A=np.load("C:/Users/Affinity/Desktop/Python_Data/arr_AB.npy")
npy_AB["B1d"]

array([[ 2,  5,  3],
       [ 6,  7, 33],
       [ 4,  2,  7],
       [ 7,  9,  4]])

### 텍스트 파일 불러오기와 저장하기

In [184]:
A=np.loadtxt('C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt', 
             skiprows=5, delimiter="\t")
print(A.mean(axis=0))

[112.7375 198.375   59.25  ]


In [185]:
A=np.loadtxt('C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt', 
             skiprows=5, delimiter="\t", usecols=(0,2))
print(A.mean(axis=0))

[112.7375  59.25  ]


In [188]:
A=np.arange(8).reshape(4,2)
B=np.array([[3,5,7,2],[4,3,6,2]])
C=np.array([[5,3,6,4],[7,6,4,5],[5,8,4,2],[6,5,3,7]])
print(A);print(B);print(C)
print(np.dot(B,A), np.diag(C))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[3 5 7 2]
 [4 3 6 2]]
[[5 3 6 4]
 [7 6 4 5]
 [5 8 4 2]
 [6 5 3 7]]
[[50 67]
 [42 57]] [5 6 4 7]


### 선형대수학

In [4]:
steel = np.loadtxt("C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt",
                   skiprows=5, delimiter="\t")
y=steel[:,0].copy()
X=steel.copy()
X[:,0]=1
print(X,y)

[[  1. 195.  57.]
 [  1. 179.  61.]
 [  1. 205.  60.]
 [  1. 204.  62.]
 [  1. 201.  61.]
 [  1. 184.  54.]
 [  1. 210.  58.]
 [  1. 209.  61.]] [ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]


In [5]:
np.linalg.lstsq(X,y)

C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([-5.54311223e+02, -1.79739607e-01,  1.18599927e+01]),
 array([2340.88393765]),
 3,
 array([5.86352311e+02, 8.94176555e+00, 1.09839713e-01]))

#### 회귀계수 값들 추정됨 (beta0, beta1, beta2)

In [8]:
import numpy as np
b=np.linalg.lstsq(X,y)[0]
New_x=np.array([1,200,60])
print(b,x)

C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


NameError: name 'x' is not defined