## 공분산과 상관계수

### 공분산 구하기

In [205]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

steel_data = np.loadtxt('C:/Users/Affinity/Desktop/Python_Data/ch02_data/steel.txt', 
                        skiprows=5,delimiter='\t')
steel_data

array([[ 81.4, 195. ,  57. ],
       [122.2, 179. ,  61. ],
       [101.7, 205. ,  60. ],
       [175.6, 204. ,  62. ],
       [150.3, 201. ,  61. ],
       [ 64.8, 184. ,  54. ],
       [ 92.1, 210. ,  58. ],
       [113.8, 209. ,  61. ]])

In [206]:
df=DataFrame(steel_data, columns=["y","x1","x2"])
df["x21"]=df.x2*10
df

y     x1    x2    x21
0   81.4  195.0  57.0  570.0
1  122.2  179.0  61.0  610.0
2  101.7  205.0  60.0  600.0
3  175.6  204.0  62.0  620.0
4  150.3  201.0  61.0  610.0
5   64.8  184.0  54.0  540.0
6   92.1  210.0  58.0  580.0
7  113.8  209.0  61.0  610.0

In [8]:
print("x1과 y의 공분산\n{0}\n".format(df.x1.cov(df.y)))
print("공분산행렬\n{0}".format(df.cov()))

x1과 y의 공분산
108.85535714285713

공분산행렬
               y          x1         x2         x21
y    1325.868393  108.855357  85.246429  852.464286
x1    108.855357  131.982143  11.178571  111.785714
x2     85.246429   11.178571   7.357143   73.571429
x21   852.464286  111.785714  73.571429  735.714286


#### x21과 x2의 공분산이 10배 차이난다! (공분산은 단위에 따라 달라짐)

### 상관계수 구하기

In [9]:
df.x1.corr(df.y)

0.2602208017100887

#### 모든 변수의 상관계수 행렬 구하기: 공분산과는 다르게, 단위와 상관없이 관계의 정도가 동일하다.

#### 따라서, 두 변수의 관계를 비교할땐 보통은 상관계수로

In [10]:
df.corr()

y        x1        x2       x21
y    1.000000  0.260221  0.863120  0.863120
x1   0.260221  1.000000  0.358735  0.358735
x2   0.863120  0.358735  1.000000  1.000000
x21  0.863120  0.358735  1.000000  1.000000

#### 해석: y에 x1보다 x2가 더 영향을 줄 가능성이 높다.
#### 관계의 방향: 부호, 관계의 정도 (크기): 절대값

## 유일 값, 값 세기

In [11]:
s=Series([22,13,14,22,14,11,14])
s.unique()

array([22, 13, 14, 11], dtype=int64)

In [12]:
s.value_counts()

14    3
22    2
13    1
11    1
dtype: int64

In [14]:
s=Series([32,43,52,32,43])
s.isin([32,52])

0     True
1    False
2     True
3     True
4    False
dtype: bool

In [15]:
data={"att":[5,7,5,7], "hw":[7,9,8,6], "mid":[28,30,29,30], "fin":[27,31,27,25]}
df=DataFrame(data)
df.att.value_counts()

7    2
5    2
Name: att, dtype: int64

In [19]:
# 데이터프레임이니까 데이터프레임에 포함된 메소드 쓸 수 있음. 
result=df.apply(pd.value_counts).fillna(0) # 데이터프레임의 메소드들 중 하나. 
#result.fillna(0) 이렇게 따로 해도된다 but 두 줄 
result

att   hw  mid  fin
5   2.0  0.0  0.0  0.0
6   0.0  1.0  0.0  0.0
7   2.0  1.0  0.0  0.0
8   0.0  1.0  0.0  0.0
9   0.0  1.0  0.0  0.0
25  0.0  0.0  0.0  1.0
27  0.0  0.0  0.0  2.0
28  0.0  0.0  1.0  0.0
29  0.0  0.0  1.0  0.0
30  0.0  0.0  2.0  0.0
31  0.0  0.0  0.0  1.0

### 누락된 데이터 처리

In [23]:
s=Series(["kim",np.nan,"lee","kang",None,"cho"])
s

0     kim
1     NaN
2     lee
3    kang
4    None
5     cho
dtype: object

In [26]:
s.isnull()

0    False
1     True
2    False
3    False
4     True
5    False
dtype: bool

In [27]:
~s.isnull()

0     True
1    False
2     True
3     True
4    False
5     True
dtype: bool

In [30]:
s.fillna("NULL")

0     kim
1    NULL
2     lee
3    kang
4    NULL
5     cho
dtype: object

In [33]:
s=Series([64,86,57,27,np.nan,57,48,np.nan,np.nan, np.nan])
s

0    64.0
1    86.0
2    57.0
3    27.0
4     NaN
5    57.0
6    48.0
7     NaN
8     NaN
9     NaN
dtype: float64

In [36]:
s.dropna()

0    64.0
1    86.0
2    57.0
3    27.0
5    57.0
6    48.0
dtype: float64

#### 또 다른 경우엔 데이터프레임으로 되어 있는 경우

In [207]:
s=DataFrame({"att":[7,np.nan,7,8,np.nan], "hw":[7,6,7,8,np.nan],
            "mid":[23,15, np.nan,8,np.nan],"fin":[23,np.nan,25,30,np.nan]})
s

att   hw   mid   fin
0  7.0  7.0  23.0  23.0
1  NaN  6.0  15.0   NaN
2  7.0  7.0   NaN  25.0
3  8.0  8.0   8.0  30.0
4  NaN  NaN   NaN   NaN

In [40]:
s.dropna()

att   hw   mid   fin
0  7.0  7.0  23.0  23.0
3  8.0  8.0   8.0  30.0

In [41]:
s.dropna(how="all") # 모든 변수의 값이 na인 행만 제거 

att   hw   mid   fin
0  7.0  7.0  23.0  23.0
1  NaN  6.0  15.0   NaN
2  7.0  7.0   NaN  25.0
3  8.0  8.0   8.0  30.0

In [42]:
s.dropna(axis=1) # 열 기준으로 데이터 제거 

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [47]:
s.dropna(axis=1,thresh=4) # 최소한 4개의 데이터가 온전해야 그 행을 선택

hw
0  7.0
1  6.0
2  7.0
3  8.0
4  NaN

### 누락된 값 채우기: fillna

In [63]:
s=Series([2,5,3,4,3,np.nan,3,2,4,4,np.nan,np.nan])
s

0     2.0
1     5.0
2     3.0
3     4.0
4     3.0
5     NaN
6     3.0
7     2.0
8     4.0
9     4.0
10    NaN
11    NaN
dtype: float64

In [60]:
s.fillna(value=0) # 원본은 그대로 있고, 수정한 값을 객체로 돌려줌

0     2.0
1     5.0
2     3.0
3     4.0
4     3.0
5     0.0
6     3.0
7     2.0
8     4.0
9     4.0
10    0.0
11    0.0
dtype: float64

In [54]:
new_s=s.fillna(value=999,inplace=True)
new_s

In [55]:
s

0     2.0
1     5.0
2     3.0
3     4.0
4     3.0
5     0.0
6     3.0
7     2.0
8     4.0
9     4.0
10    0.0
11    0.0
dtype: float64

In [64]:
s.fillna(value=999,inplace=True)
s

0       2.0
1       5.0
2       3.0
3       4.0
4       3.0
5     999.0
6       3.0
7       2.0
8       4.0
9       4.0
10    999.0
11    999.0
dtype: float64

#### 데이터프레임에서도 fillna 사용가능

In [204]:
df=DataFrame({"att":[7,np.nan,7,8,np.nan], "hw":[7,6,7,8,np.nan],
            "mid":[23,15, np.nan,8,np.nan],"fin":[23,np.nan,25,30,np.nan]})
df.fillna(0)

TypeError: 'tuple' object is not callable

#### 각 변수별 평균치로 채워준다

In [68]:
df=DataFrame({"att":[7,np.nan,7,8,np.nan], "hw":[7,6,7,8,np.nan],
            "mid":[23,15, np.nan,8,np.nan],"fin":[23,np.nan,25,30,np.nan]})
df.fillna(value=df.mean()) # 

att   hw        mid   fin
0  7.000000  7.0  23.000000  23.0
1  7.333333  6.0  15.000000  26.0
2  7.000000  7.0  15.333333  25.0
3  8.000000  8.0   8.000000  30.0
4  7.333333  7.0  15.333333  26.0

In [69]:
df.fillna(value=df.median()) # 중앙값으로 대체

att   hw   mid   fin
0  7.0  7.0  23.0  23.0
1  7.0  6.0  15.0  25.0
2  7.0  7.0  15.0  25.0
3  8.0  8.0   8.0  30.0
4  7.0  7.0  15.0  25.0

## 계층적 색인
### 다중 색인

In [73]:
s=Series([2,5,3,7,5,7,np.nan,5,4,6], index=[["stat", "stat", "stat", "econ", "econ", "comp", "comp", "comp", "math", "math"],
                                            [1,2,3,2,3,1,2,3,1,2]])
s

stat  1    2.0
      2    5.0
      3    3.0
econ  2    7.0
      3    5.0
comp  1    7.0
      2    NaN
      3    5.0
math  1    4.0
      2    6.0
dtype: float64

In [74]:
s["math"] # 첫 번째 인덱스값이 mat인것을 출력해준다 

1    4.0
2    6.0
dtype: float64

In [75]:
s[["stat","math"]]

stat  1    2.0
      2    5.0
      3    3.0
math  1    4.0
      2    6.0
dtype: float64

In [76]:
s[["math","1"]] # 이렇게 하는게 아니라 

math  1    4.0
      2    6.0
dtype: float64

In [80]:
s[[("stat",1), ("stat",3)]] # 이렇게 괄호 안에 첫 번째, 두 번째 인덱스 써줌

stat  1    2.0
      3    3.0
dtype: float64

### 상위 / 하위 색인

In [81]:
s[[("stat",2),("math",2)]]

stat  2    5.0
math  2    6.0
dtype: float64

#### 또는 다음과 같이 해도 된다

In [82]:
s[["stat","math"]][:,2]

stat    5.0
math    6.0
dtype: float64

### 중첩 해제: unstack()

In [84]:
s

stat  1    2.0
      2    5.0
      3    3.0
econ  2    7.0
      3    5.0
comp  1    7.0
      2    NaN
      3    5.0
math  1    4.0
      2    6.0
dtype: float64

In [85]:
s.unstack()

1    2    3
comp  7.0  NaN  5.0
econ  NaN  7.0  5.0
math  4.0  6.0  NaN
stat  2.0  5.0  3.0

In [87]:
s.unstack().stack() # unstack했던 것을 다시 stack해줌

comp  1    7.0
      3    5.0
econ  2    7.0
      3    5.0
math  1    4.0
      2    6.0
stat  1    2.0
      2    5.0
      3    3.0
dtype: float64

In [208]:
s1=Series([2,5,3,7,5,7,np.nan,5,4,6], index=[["stat", "stat", "stat", "econ", "econ", "comp", "comp", "comp", "math", "math"],
                                            [1,2,3,2,3,1,2,3,1,2]], columns=[["서울", "서울", "경기", "경기"], ["M", "F", "M", "F"]])
s1.index.names=["dept", "cls"]
s1.columns.names=["area", "gender"]
s1

TypeError: __init__() got an unexpected keyword argument 'columns'

In [ ]:
df.loc[[("stat",1),("stat",2)]][[("서울","M"),("경기","M")]] # 이따 해보기


### 단계별 요약 통계량

## DataFrame의 열 사용

### set_index 메소드를 사용하여 열 색인을 행으로 옮기기

In [94]:
np.random.seed(123789)
data=np.random.binomial(n=10,p=0.6,size=30).reshape(10,3)
df=DataFrame(data,columns=["V1","V2","V3"])
df["V4"]=["M","F","M","M","M","F","M","F","F","M"]
df

V1  V2  V3 V4
0   8   8   6  M
1   2   7   7  F
2   6   3   8  M
3   7   4   4  M
4   5   5   7  M
5   5   6   8  F
6   5   6   6  M
7   4   4   6  F
8   3   6   6  F
9   6   8   4  M

### 변수를 색인으로

In [96]:
df1=df.set_index(keys=["V2","V4"]).sort_index()
df1

V1  V3
V2 V4        
3  M    6   8
4  F    4   6
   M    7   4
5  M    5   7
6  F    5   8
   F    3   6
   M    5   6
7  F    2   7
8  M    8   6
   M    6   4

### 색인을 변수로

In [97]:
df1.reset_index(level="V4")

V4  V1  V3
V2           
3   M   6   8
4   F   4   6
4   M   7   4
5   M   5   7
6   F   5   8
6   F   3   6
6   M   5   6
7   F   2   7
8   M   8   6
8   M   6   4

# 3. 자료 불러오기,저장하기와 자료 다듬기, 변형, 병합

In [102]:
from pandas import Series, DataFrame
from numpy import nan as NA
import pandas as pd
import numpy as np
APT=pd.read_csv('C:/Users/Affinity/Desktop/Python_Data/ch02_data/APT.csv', header=0, skiprows=7, index_col="id",encoding='utf-8')
APT

Area UseDistrict Option     FAR        Price
id                                                 
apt01   도심권  제2종 일반주거지역   풀옵션형  132.72  515.0519492
apt02   도심권  제2종 일반주거지역   풀옵션형  184.99             
apt03              상업지역    기본형          364.3195349
apt04   도심권        상업지역   풀옵션형  493.08  410.9455297
apt05   도심권       준주거지역    기본형  349.65  616.9759862
apt06   도심권  제3종 일반주거지역   풀옵션형       .  469.1517971
apt07   도심권  제3종 일반주거지역   풀옵션형   227.2  576.4762615
apt08   도심권        상업지역   풀옵션형  254.37  355.8718861
apt09   동북권                기본형  199.93  423.8123398
apt10   동북권  제2종 일반주거지역   풀옵션형  198.13  518.3137526
apt11   동북권  제2종 일반주거지역   풀옵션형  199.34  615.7635468
apt12   동북권  제3종 일반주거지역   풀옵션형  195.22  455.0302169
apt13   동북권  제2종 일반주거지역    기본형   199.5  460.6879607
apt14   동북권       준공업지역   풀옵션형  219.16  512.4777184
apt15   동북권  제2종 일반주거지역   풀옵션형  192.39  483.7566204
apt16   동북권  제2종 일반주거지역    기본형  198.94  489.1620599
apt17   동북권  제2종 일반주거지역    기본형  178.38  370.4786975
apt18   동북권  제2종 일반주거지역   풀옵션형   199.8  383.4406746
apt19   동북권  제2종 일반주거지역   풀옵션형  169.38  443.8932045
apt20   동북권  제3종 일반주거지역   풀옵션형  221.57  411.5629593
apt21   동북권  제2종 일반주거지역   풀옵션형  198.73  161.7276468
apt22   동북권  제2종 일반주거지역    기본형  184.83  309.3421324
apt23   동북권  제2종 일반주거지역   풀옵션형  199.87  310.5057298
apt24   동북권  제2종 일반주거지역    기본형  166.71  293.1051441
apt25   동북권  제2종 일반주거지역   풀옵션형  199.85  136.7989056
apt26   동북권  제2종 일반주거지역   풀옵션형  199.85  128.9930951
apt27   동북권  제2종 일반주거지역   풀옵션형  199.92  123.4567901
apt28   동북권  제2종 일반주거지역   풀옵션형  199.82  123.9669421
apt29   동북권  제2종 일반주거지역   풀옵션형  188.82  327.6417783
apt30   동북권  제3종 일반주거지역   풀옵션형  194.04  288.2945467
...     ...         ...    ...     ...          ...
apt371  서남권        상업지역   풀옵션형  379.69  318.4713376
apt372  서남권  제2종 일반주거지역    기본형  190.19  258.4883815
apt373  서남권  제2종 일반주거지역    기본형  116.68  262.0423892
apt374  서남권  제2종 일반주거지역    기본형  198.02  288.5272377
apt375  서남권  제3종 일반주거지역   풀옵션형  144.45  232.7637006
apt376  서남권  제2종 일반주거지역    기본형  199.48  194.2393612
apt377  서남권  제2종 일반주거지역    기본형  178.98  202.9520295
apt378  서남권  제2종 일반주거지역   풀옵션형   198.7  298.4327467
apt379  동북권  제2종 일반주거지역   풀옵션형  199.96   314.045169
apt380  동북권  제1종 일반주거지역   풀옵션형   170.8  310.5698738
apt381  동북권       준주거지역    기본형  333.45   298.614429
apt382  동북권  제2종 일반주거지역   풀옵션형  140.05  230.6621595
apt383  동북권  제1종 일반주거지역   풀옵션형  149.96  231.5948871
apt384  동북권  제1종 일반주거지역   풀옵션형   146.5   388.299983
apt385  동북권  제2종 일반주거지역   풀옵션형  194.06  266.4709971
apt386  동북권  제2종 일반주거지역   풀옵션형  182.08  339.1075819
apt387  동북권  제2종 일반주거지역   풀옵션형  198.68  346.9101629
apt388  동북권  제2종 일반주거지역   풀옵션형  199.53   297.350573
apt389  동북권  제2종 일반주거지역   풀옵션형  195.69  397.9504697
apt390  동북권  제2종 일반주거지역   풀옵션형  195.57   277.354336
apt391  동북권  제2종 일반주거지역    기본형  199.68  260.2758248
apt392  동북권  제2종 일반주거지역   풀옵션형  199.47  330.3763735
apt393  동북권       준주거지역    기본형  305.84  370.9616829
apt394  동북권  제2종 일반주거지역   풀옵션형  152.16  289.6081772
apt395  동북권  제2종 일반주거지역   풀옵션형  116.54  399.5875226
apt396  서남권  제2종 일반주거지역    기본형  183.71  196.8503937
apt397  서남권  제2종 일반주거지역   풀옵션형  188.03  105.1154484
apt398  도심권  제2종 일반주거지역    기본형  181.24  235.9284512
apt399  도심권  제1종 일반주거지역   풀옵션형  149.87  294.8475538
apt400  도심권  제1종 일반주거지역    기본형  142.23  221.3902002

[400 rows x 5 columns]

In [104]:
APT.head(7)

Area UseDistrict Option     FAR        Price
id                                                
apt01  도심권  제2종 일반주거지역   풀옵션형  132.72  515.0519492
apt02  도심권  제2종 일반주거지역   풀옵션형  184.99             
apt03             상업지역    기본형          364.3195349
apt04  도심권        상업지역   풀옵션형  493.08  410.9455297
apt05  도심권       준주거지역    기본형  349.65  616.9759862
apt06  도심권  제3종 일반주거지역   풀옵션형       .  469.1517971
apt07  도심권  제3종 일반주거지역   풀옵션형   227.2  576.4762615

### 결측값 처리: na_values

In [108]:
APT=pd.read_csv('C:/Users/Affinity/Desktop/Python_Data/ch02_data/APT.csv', header=0, skiprows=7, index_col="id",encoding='utf-8',
               na_values=[" ","."])
APT.head(10)

Area UseDistrict Option     FAR       Price
id                                               
apt01  도심권  제2종 일반주거지역   풀옵션형  132.72  515.051949
apt02  도심권  제2종 일반주거지역   풀옵션형  184.99         NaN
apt03  NaN        상업지역    기본형     NaN  364.319535
apt04  도심권        상업지역   풀옵션형  493.08  410.945530
apt05  도심권       준주거지역    기본형  349.65  616.975986
apt06  도심권  제3종 일반주거지역   풀옵션형     NaN  469.151797
apt07  도심권  제3종 일반주거지역   풀옵션형  227.20  576.476262
apt08  도심권        상업지역   풀옵션형  254.37  355.871886
apt09  동북권         NaN    기본형  199.93  423.812340
apt10  동북권  제2종 일반주거지역   풀옵션형  198.13  518.313753

### header=None 하고 변수명 직접 입력

In [127]:
APT=pd.read_csv('C:/Users/Affinity/Desktop/Python_Data/ch02_data/APT.csv', header=None, names=["V1","V2","V3","V4","V5"], 
                skiprows=10, nrows=7,index_col=0,encoding='utf-8',na_values=[" ","."])
APT.head(4) # 앞쪽 4개를 출력한다

V1          V2    V3      V4          V5
apt03  NaN        상업지역   기본형     NaN  364.319535
apt04  도심권        상업지역  풀옵션형  493.08  410.945530
apt05  도심권       준주거지역   기본형  349.65  616.975986
apt06  도심권  제3종 일반주거지역  풀옵션형     NaN  469.151797

In [121]:
APT=pd.read_csv('C:/Users/Affinity/Desktop/Python_Data/ch02_data/APT.csv', header=None, names=["V1","V2","V3","V4","V5"], 
                skiprows=10, nrows=7,index_col=0,encoding='utf-8',na_values=[" ","."])
APT.tail(4) # 뒤쪽 4개를 출력한다

V1          V2    V3      V4          V5
apt06  도심권  제3종 일반주거지역  풀옵션형     NaN  469.151797
apt07  도심권  제3종 일반주거지역  풀옵션형  227.20  576.476262
apt08  도심권        상업지역  풀옵션형  254.37  355.871886
apt09  동북권         NaN   기본형  199.93  423.812340

In [124]:
APT=pd.read_csv('C:/Users/Affinity/Desktop/Python_Data/ch02_data/APT.csv', header=0, 
                skiprows=7, nrows=7,index_col=0,encoding='utf-8',na_values=[" ","."])
APT["Price"]

id
apt01    515.051949
apt02           NaN
apt03    364.319535
apt04    410.945530
apt05    616.975986
apt06    469.151797
apt07    576.476262
Name: Price, dtype: float64

### 텍스트 파일 저장하기

In [128]:
APT.to_csv("C:/Users/Affinity/Desktop/Python_Data/ch02_data/APTSave.txt", sep='|', na_rep="NULL", index=False, header=True, columns=["V1","V4","V5"])

### 데이터 합치기

In [135]:
df1=DataFrame({"key":["a","b","a","a","c","b"], "V1":range(6)})
df2=DataFrame({"key":["a","b","d"],"V2":[3,6,4]})
print(df1,"\n\n",df2)

  key  V1
0   a   0
1   b   1
2   a   2
3   a   3
4   c   4
5   b   5 

   key  V2
0   a   3
1   b   6
2   d   4


#### 디폴트는 동일한 변수 

#### key라는 변수를 기준으로 양쪽 둘다있는 변수 결합해준다

In [136]:
pd.merge(df1,df2, on="key")

key  V1  V2
0   a   0   3
1   a   2   3
2   a   3   3
3   b   1   6
4   b   5   6

#### 서로 변수 이름이 다를 경우

In [139]:
df1=DataFrame({"key1":["a","b","a","a","c","b"], "V1":range(6)})
df2=DataFrame({"key2":["a","b","d"],"V2":[3,6,4]})
print(df1,"\n\n",df2)

  key1  V1
0    a   0
1    b   1
2    a   2
3    a   3
4    c   4
5    b   5 

   key2  V2
0    a   3
1    b   6
2    d   4


In [141]:
pd.merge(df1,df2,left_on="key1",right_on="key2")

key1  V1 key2  V2
0    a   0    a   3
1    a   2    a   3
2    a   3    a   3
3    b   1    b   6
4    b   5    b   6

In [143]:
df1=DataFrame({"key1":["a","b","a","a","c","b"], "gender":["M","M","F","F","M","M"],"v1":range(6)})
df2=DataFrame({"key2":["a","b","d"],"sex":["F","M","F"],"v2":[3,6,4]})
print(df1,"\n\n",df2)

  key1 gender  v1
0    a      M   0
1    b      M   1
2    a      F   2
3    a      F   3
4    c      M   4
5    b      M   5 

   key2 sex  v2
0    a   F   3
1    b   M   6
2    d   F   4


#### 두 변수 이상을 key값으로 하는 경우

In [144]:
pd.merge(df1,df2,left_on=["key1","gender"],right_on=["key2","sex"])

key1 gender  v1 key2 sex  v2
0    b      M   1    b   M   6
1    b      M   5    b   M   6
2    a      F   2    a   F   3
3    a      F   3    a   F   3

In [146]:
pd.merge(df1,df2,left_on="key1",right_on="key2",how="outer")

key1 gender   v1 key2  sex   v2
0    a      M  0.0    a    F  3.0
1    a      F  2.0    a    F  3.0
2    a      F  3.0    a    F  3.0
3    b      M  1.0    b    M  6.0
4    b      M  5.0    b    M  6.0
5    c      M  4.0  NaN  NaN  NaN
6  NaN    NaN  NaN    d    F  4.0

In [148]:
pd.merge(df1,df2,left_on="key1",right_on="key2",how="left")

key1 gender  v1 key2  sex   v2
0    a      M   0    a    F  3.0
1    b      M   1    b    M  6.0
2    a      F   2    a    F  3.0
3    a      F   3    a    F  3.0
4    c      M   4  NaN  NaN  NaN
5    b      M   5    b    M  6.0

In [209]:
df1=DataFrame({"key1":["a","b","a","a","c","b"],"gender":["M","M","F","F","M","M"], "v1":range(6)})
df2=DataFrame({"v1":[99,999,9], "v2":[3,6,4]}, index=["a","c","b"])
print(df1,"\n\n",df2)


  key1 gender  v1
0    a      M   0
1    b      M   1
2    a      F   2
3    a      F   3
4    c      M   4
5    b      M   5 

     v1  v2
a   99   3
c  999   6
b    9   4


In [160]:
pd.merge(df1,df2,left_on=["key1"],right_index=True,how="outer",sort=True)

key1 gender  v1_x  v1_y  v2
0    a      M     0    99   3
2    a      F     2    99   3
3    a      F     3    99   3
1    b      M     1     9   4
5    b      M     5     9   4
4    c      M     4   999   6

#### 위의 df1에 인덱스 넣어줌

In [161]:
df1=DataFrame({"key1":["a","b","a","a","c","b"],"gender":["M","M","F","F","M","M"],"v1":range(6)},index=["a","b","a","a","c","b"])
df2=DataFrame({"v1":[99,999,9], "v2":[3,6,4]}, index=["a","d","b"])
print(df1,"\n\n",df2)

  key1 gender  v1
a    a      M   0
b    b      M   1
a    a      F   2
a    a      F   3
c    c      M   4
b    b      M   5 

     v1  v2
a   99   3
d  999   6
b    9   4


In [162]:
pd.merge(df1,df2,left_on=["key1"],right_index=True,how="outer",sort=True)

key1 gender  v1_x   v1_y   v2
a    a      M   0.0   99.0  3.0
a    a      F   2.0   99.0  3.0
a    a      F   3.0   99.0  3.0
b    b      M   1.0    9.0  4.0
b    b      M   5.0    9.0  4.0
c    c      M   4.0    NaN  NaN
b    d    NaN   NaN  999.0  6.0

### index를 이용한 결합은 join 메소드 사용으로도 가능

In [163]:
df1.join(df2,lsuffix='_left',rsuffix="_right",how="outer")

key1 gender  v1_left  v1_right   v2
a    a      M      0.0      99.0  3.0
a    a      F      2.0      99.0  3.0
a    a      F      3.0      99.0  3.0
b    b      M      1.0       9.0  4.0
b    b      M      5.0       9.0  4.0
c    c      M      4.0       NaN  NaN
d  NaN    NaN      NaN     999.0  6.0

### 축에 따라 데이터 붙이기: NumPy의 배열을 연결하는 concatenate 함수와 유사

In [165]:
arr1=np.arange(12).reshape(3,4)
arr2=np.arange(8).reshape(2,4)
print(arr1,"\n\n",arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[0 1 2 3]
 [4 5 6 7]]


#### 행 결합

In [169]:
np.concatenate([arr1,arr2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

### 시리즈 결합

In [168]:
s1=Series([0,2,3],index=["a","b","c"])
s2=Series([2,3,4,5],index=["a","c","d","e"])
s3=Series([1,3],index=["e","f"])
print(s1,"\n",s2,"\n",s3)

a    0
b    2
c    3
dtype: int64 
 a    2
c    3
d    4
e    5
dtype: int64 
 e    1
f    3
dtype: int64


#### 행 이어붙이기

In [171]:
pd.concat([s1,s2,s3])

a    0
b    2
c    3
a    2
c    3
d    4
e    5
e    1
f    3
dtype: int64

In [175]:
pd.concat([s1,s2,s3],axis=0,sort=True)

a    0
b    2
c    3
a    2
c    3
d    4
e    5
e    1
f    3
dtype: int64

#### 열결합: 각각의 시리즈를 변수로 하는

In [174]:
pd.concat([s1,s2,s3],axis=1,sort=True)

0    1    2
a  0.0  2.0  NaN
b  2.0  NaN  NaN
c  3.0  3.0  NaN
d  NaN  4.0  NaN
e  NaN  5.0  1.0
f  NaN  NaN  3.0

#### 결합 조건에 따른 열 결합

In [176]:
pd.concat([s1,s2],axis=1,join="outer",sort=True)

0    1
a  0.0  2.0
b  2.0  NaN
c  3.0  3.0
d  NaN  4.0
e  NaN  5.0

In [177]:
pd.concat([s1,s2],axis=1,join="inner",sort=True)

0  1
a  0  2
c  3  3

#### 열 결합시 join할 행 선택: join_axes 활용

In [179]:
pd.concat([s1,s2,s3],axis=1,join="outer",sort=True,join_axes=[["a","e"]])

0  1    2
a  0.0  2  NaN
e  NaN  5  1.0

#### 행 결합(이어 연결하기)에서 계층 색인 생성: S1,S2,S3를 각각 계층으로 결합

In [180]:
pd.concat([s1,s2,s3],axis=0,keys=["AA","BB","CC"])

AA  a    0
    b    2
    c    3
BB  a    2
    c    3
    d    4
    e    5
CC  e    1
    f    3
dtype: int64

#### 이열 결합(merge)에서 열 색인 생성 (join 지정 안해주면 무조건 outer: 하나라도 있을 시 들어감)

In [181]:
pd.concat([s1,s2,s3],axis=1,keys=["AA","BB","CC"],sort=True)

AA   BB   CC
a  0.0  2.0  NaN
b  2.0  NaN  NaN
c  3.0  3.0  NaN
d  NaN  4.0  NaN
e  NaN  5.0  1.0
f  NaN  NaN  3.0

#### DataFrame 결합

In [184]:
df1=DataFrame(np.arange(12).reshape(3,4),index=["a","b","c"],columns=["v1","v2","v3","v4"])
df2=DataFrame(np.arange(8).reshape(2,4),index=["b","d"], columns=["x1","x2","x3","x4"])
print(df1,"\n\n",df2)

   v1  v2  v3  v4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11 

    x1  x2  x3  x4
b   0   1   2   3
d   4   5   6   7


In [185]:
pd.concat([df1,df2],axis=0,sort=True)

v1   v2    v3    v4   x1   x2   x3   x4
a  0.0  1.0   2.0   3.0  NaN  NaN  NaN  NaN
b  4.0  5.0   6.0   7.0  NaN  NaN  NaN  NaN
c  8.0  9.0  10.0  11.0  NaN  NaN  NaN  NaN
b  NaN  NaN   NaN   NaN  0.0  1.0  2.0  3.0
d  NaN  NaN   NaN   NaN  4.0  5.0  6.0  7.0

#### 기존의 index를 무시하고, range 범위로 새로 인덱싱하기: ignore_index=True

In [187]:
pd.concat([df1,df2],axis=1,sort=True, ignore_index=True)

0    1     2     3    4    5    6    7
a  0.0  1.0   2.0   3.0  NaN  NaN  NaN  NaN
b  4.0  5.0   6.0   7.0  0.0  1.0  2.0  3.0
c  8.0  9.0  10.0  11.0  NaN  NaN  NaN  NaN
d  NaN  NaN   NaN   NaN  4.0  5.0  6.0  7.0

In [189]:
pd.concat([df1,df2],axis=1,sort=True, keys=["Df1","Df2"]) # 계층

Df1                   Df2               
    v1   v2    v3    v4   x1   x2   x3   x4
a  0.0  1.0   2.0   3.0  NaN  NaN  NaN  NaN
b  4.0  5.0   6.0   7.0  0.0  1.0  2.0  3.0
c  8.0  9.0  10.0  11.0  NaN  NaN  NaN  NaN
d  NaN  NaN   NaN   NaN  4.0  5.0  6.0  7.0

### 중복 제거: duplicated

In [219]:
df=DataFrame({"name":["kim","kim","lee","lee","lee","kim"],
              "score":[1,2,2,2,3,1]})
df

name  score
0  kim      1
1  kim      2
2  lee      2
3  lee      2
4  lee      3
5  kim      1

In [220]:
df.duplicated(subset="name")

0    False
1     True
2    False
3     True
4     True
5     True
dtype: bool

## 함수나 매핑 이용해 데이터 변형

In [210]:
import numpy

df=DataFrame({"name":["kim","lee","bae","cho","kang"],"sex":[1,2,2,1,1],
              "home":["마포","수지","처인","용산","종로"],"income":[250,195,325,210,274]})
num_to_str={1:"남",2:"여"}
to_city={"마포":"서울","용산":"서울","종로":"서울","수지":"용인","처인":"용인"}
df

name  sex home  income
0   kim    1   마포     250
1   lee    2   수지     195
2   bae    2   처인     325
3   cho    1   용산     210
4  kang    1   종로     274

In [211]:
def f(x):
    return x*0.015
df["gender"]=df["sex"].map(num_to_str)
df["city"]=df["home"].map(to_city)
df["remium"]=df["income"].map(f)
df

name  sex home  income gender city  remium
0   kim    1   마포     250      남   서울   3.750
1   lee    2   수지     195      여   용인   2.925
2   bae    2   처인     325      여   용인   4.875
3   cho    1   용산     210      남   서울   3.150
4  kang    1   종로     274      남   서울   4.110

### 값  치환하기

In [223]:
df=DataFrame({"name":["kim","lee","bae","cho","kang"],"sex":[1,2,3,4,1],
              "home":["마포",np.nan,"처인","용산","종로"],"income":[250,-999,325,210,np.inf]})
num_to_str={1:"남",2:"여"}
to_city={"마포":"서울","용산":"서울","종로":"서울","수지":"용인","처인":"용인"}
df

name  sex home  income
0   kim    1   마포   250.0
1   lee    2  NaN  -999.0
2   bae    3   처인   325.0
3   cho    4   용산   210.0
4  kang    1   종로     inf

#### .replace 메소드를 이용해서 특정한 값을 특정한 값으로 치환 (전체적으로 바꾸고 싶을때!!!)

In [224]:
df1=df.replace([np.nan,3,4],[9999,1,2])
df1

name  sex  home  income
0   kim    1    마포   250.0
1   lee    2  9999  -999.0
2   bae    1    처인   325.0
3   cho    2    용산   210.0
4  kang    1    종로     inf

#### 또는 dictionary 안의 dictionary를 사용해도 된다 (전체적으로 말고 특정 변수 (e.g. sex내에서 3->1,4->2)내에서 치환 정의하고 싶을 때!!)

In [225]:
df1=df.replace({"sex":{3:1,4:2},"income":{-999:np.nan,np.inf:np.nan}})
df1

name  sex home  income
0   kim    1   마포   250.0
1   lee    2  NaN     NaN
2   bae    1   처인   325.0
3   cho    2   용산   210.0
4  kang    1   종로     NaN

#### 1:1매핑 말고 다대일 매핑

In [226]:
df2=df1.replace({"home":np.nan,"income":np.nan},np.inf)
df2

name  sex home  income
0   kim    1   마포   250.0
1   lee    2  inf     inf
2   bae    1   처인   325.0
3   cho    2   용산   210.0
4  kang    1   종로     inf

## 