## 난수

In [1]:
import numpy as np

In [7]:
x=np.array([[1,3,6],[1,5,4],[1,3,6],[1,4,6],[1,7,3],[1,8,4]])
x
beta=np.array([1,-2.5,5.5])
e=np.random.normal(loc=0,scale=2,size=10) # 오차항
y=np.dot(x,beta)
print(x,beta,y)

[[1 3 6]
 [1 5 4]
 [1 3 6]
 [1 4 6]
 [1 7 3]
 [1 8 4]] [ 1.  -2.5  5.5] [26.5 10.5 26.5 24.   0.   3. ]


# pandas

In [8]:
# numpy 단점: 같은 종류의 자료만 저장 가능
np.array([3,2,"A"]) # 숫자 문자 혼합시키면 다 문자로 인식

array(['3', '2', 'A'], dtype='<U11')

In [12]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd
Exam=Series([2,3,4,4])
Exam.index # 0부터 1씩 증분하는 수열

RangeIndex(start=0, stop=4, step=1)

In [18]:
Exam=Series([2,3,4,4], index=["kim", "lee", "cho", "kang"]) # 인덱스 따로 지정해줄수도 있다. 
print(Exam, Exam.index)
# 색인가지고 데이터 접근하기 (인덱싱)
print(Exam[["lee", "kang"]])


kim     2
lee     3
cho     4
kang    4
dtype: int64 Index(['kim', 'lee', 'cho', 'kang'], dtype='object')
lee     3
kang    4
dtype: int64


In [29]:
Exam=Series([2,3,6,9,3,5,7,9,3,1], index=["A","B","C","D","E","F","G","H","I","J"])
b_Result=(Exam>=4)&(Exam<8)
print(b_Result, "\n""\n""\n", Exam[b_Result])
print("\n""\n""\n",np.sqrt(Exam[(Exam>=4)&(Exam<8)])) # 여기서도 numpy함수 사용 가능

A    False
B    False
C     True
D    False
E    False
F     True
G     True
H    False
I    False
J    False
dtype: bool 


 C    6
F    5
G    7
dtype: int64



 C    2.449490
F    2.236068
G    2.645751
dtype: float64


In [32]:
dic={"kim":25,"lee":45,"cho":13} # dictionary 형태로 넣어주면 바로 인덱스랑 value로 넣어줌
Exam=Series(dic)
print(Exam,"\n""\n""\n")
Exam2=Series(dic,index=["lee","kang","cho","kim"]) # 사전의 키와 색인을 비교 (결측값은 NaN)
print(Exam2,"\n""\n""\n")

kim    25
lee    45
cho    13
dtype: int64 



lee     45.0
kang     NaN
cho     13.0
kim     25.0
dtype: float64 





In [39]:
dic={"kim":25,"lee":45,"cho":13} # dictionary 형태로 넣어주면 바로 인덱스랑 value로 넣어줌
Exam1=Series(dic)
Exam2=Series([56,75,85,96], index=["cho","kim","kang","lee"])
print(Exam1,"\n\n\n",Exam2,"\n\n\n",Exam1+Exam2)
Result=Exam1+Exam2
Result.name="성적"
Result.index.name="choi" # 새로운 색인 추가 (빈값)
Result

kim    25
lee    45
cho    13
dtype: int64 


 cho     56
kim     75
kang    85
lee     96
dtype: int64 


 cho      69.0
kang      NaN
kim     100.0
lee     141.0
dtype: float64


choi
cho      69.0
kang      NaN
kim     100.0
lee     141.0
Name: 성적, dtype: float64

### Dictionary로 DataFrame 만들기

In [40]:
dic={"gender":["M","F","F","M"], "mid":[35,56,35,34], "fin":[45, 76, 88, 79]} # 사전형에서는 key가 변수명으로 들어감
Exam=DataFrame(dic)
Exam

gender  mid  fin
0      M   35   45
1      F   56   76
2      F   35   88
3      M   34   79

In [41]:
dic={"gender":["M","F","F","M"], "mid":[35,56,35,34], "fin":[45, 76, 88, 79]} # 사전형에서는 key가 변수명으로 들어감
Exam=DataFrame(dic, columns=["fin", "gender", "mid"])
Exam

fin gender  mid
0   45      M   35
1   76      F   56
2   88      F   35
3   79      M   34

In [43]:
dic={"gender":["M","F","F","M"], "mid":[35,56,35,34], "fin":[45, 76, 88, 79]} 
Exam=DataFrame(dic, columns=["fin", "gender", "mid", "a"]) # 없는 index 추가하며 누락값으로 처리 
Exam

fin gender  mid    a
0   45      M   35  NaN
1   76      F   56  NaN
2   88      F   35  NaN
3   79      M   34  NaN

In [44]:
dic={"gender":["M","F","F","M"], "mid":[35,56,35,34], "fin":[45, 76, 88, 79]} 
Exam=DataFrame(dic, columns=["fin", "gender", "mid", "att"], index=["A","B","C","D"]) # 행 인덱스도 index= 로 처리 
Exam

fin gender  mid  att
A   45      M   35  NaN
B   76      F   56  NaN
C   88      F   35  NaN
D   79      M   34  NaN

### Dictionary말고 배열로 dataframe 만드는 경우
#### 배열은 기본적으로 열이 변수

In [48]:
arr=np.array([["M","F","F","M"],[25, 56, 35, 34], [45, 76, 88, 79]])
Exam=DataFrame(arr)
Exam

0   1   2   3
0   M   F   F   M
1  25  56  35  34
2  45  76  88  79

In [56]:
arr=np.array([[3,5,7,2],[25, 56, 35, 34], [45, 76, 88, 79]]) # 배열은 기본적으로 열이 변수 (or Transpose 시켜주면 됨)
Exam=DataFrame(arr.T, columns=["V1", "V2", "V3"], index=["A", "B", "C", "D"])
print(Exam.values)
print(Exam)
print(Exam.index)

[[ 3 25 45]
 [ 5 56 76]
 [ 7 35 88]
 [ 2 34 79]]
   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79
Index(['A', 'B', 'C', 'D'], dtype='object')


### 인덱싱

In [57]:
Exam.ix["B"] # 결과는 시리즈 값으로 돌려받는다

C:\ProgramData\Anaconda3\envs\mypython\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


V1     5
V2    56
V3    76
Name: B, dtype: int32

#### ix는 없어진다는 경고문 뜨므로 loc나 iloc 대신 쓰면 됨

In [58]:
Exam.loc["B"] # 하나는 시리즈로 반환

V1     5
V2    56
V3    76
Name: B, dtype: int32

In [59]:
Exam.loc[["B","A"]] # 두 개 이상 행을 출력하면 데이터프레임으로 반환

V1  V2  V3
B   5  56  76
A   3  25  45

In [60]:
Exam.iloc[1] # 아까처럼 인덱스 번호 

V1     5
V2    56
V3    76
Name: B, dtype: int32

In [61]:
Exam.iloc[[2,0]]

V1  V2  V3
C   7  35  88
A   3  25  45

### 열 인덱스 지정하는 또 다른 방법:
#### 1. 대괄호안에 변수이름 (두 개 이상 불러올때 편리)

In [67]:
Exam[["V3", "V1"]]

V3  V1
A  45   3
B  76   5
C  88   7
D  79   2

#### 2.메소드

In [64]:
# 하나의 변수만 지정하면 DataFrame이름.변수
Exam.V3

A    45
B    76
C    88
D    79
Name: V3, dtype: int32

### DataFrame과 Series는 색인을 기준으로 결합

In [71]:
Exam=DataFrame(arr.T, columns=["V1", "V2", "V3"], index=["A", "B", "C", "D"])
gender=Series(["남","여","남","남"], index=["D","A","E","B"])
print(Exam,"\n",gender)


   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79 
 D    남
A    여
E    남
B    남
dtype: object


In [75]:
Exam=DataFrame(arr.T, columns=["V1", "V2", "V3"], index=["A", "B", "C", "D"])
gender=Series(["남","여","남","남"], index=["D","A","E","B"])
# 새로운 열 추가
Exam["gender"]=gender # 매칭을 해서 넣어준다
Exam # 기존 데이터에 없는 것은 결합되지 않는다 (E)

V1  V2  V3 gender
A   3  25  45      여
B   5  56  76      남
C   7  35  88    NaN
D   2  34  79      남

#### 데이터 뽑기

In [77]:
Exam.iloc[[2,3]][["gender","V1"]] # 행 인덱스와 변수명

gender  V1
C    NaN   7
D      남   2

In [78]:
Exam.iloc[[2,3]].gender # 변수 하나만 보고싶을땐 .변수이름 (메소드) 하면 된다

C    NaN
D      남
Name: gender, dtype: object

In [79]:
Exam.loc[["C","A"]].gender # 아니면 loc먼저

C    NaN
A      여
Name: gender, dtype: object

## 재색인

In [81]:
obj=Series([2.5,6.4,7.8,6.5], index=["kim","cho","bae", "lee"])
print(obj)
obj1=obj.reindex(["lee","kim","bae","cho","choi"])
print("\n\n\n",obj1)

kim    2.5
cho    6.4
bae    7.8
lee    6.5
dtype: float64



 lee     6.5
kim     2.5
bae     7.8
cho     6.4
choi    NaN
dtype: float64


In [82]:
Ex=Series([3,5,2,6])
Ex.reindex([2,0,3,5,1], fill_value=0) # 누락값들은 자동적으로 기본값 (0)으로 채우기

2    2
0    3
3    6
5    0
1    5
dtype: int64

In [84]:
Ex=Series([3,5,2,6])
Ex.reindex([2,0,3,5,1], method="ffill")

2    2
0    3
3    6
5    6
1    5
dtype: int64

In [88]:
Exam=DataFrame(arr.T, columns=["V1", "V2", "V3"], index=["A", "B", "C", "D"])
gender=Series(["남","여","남","남"], index=["D","A","E","B"])
# 새로운 열 추가
Exam["gender"]=gender # 매칭을 해서 넣어준다
Exam=Exam.reindex(["C","A","B","F","D"], method="ffill")
Exam # 기존 데이터에 없는 것은 결합되지 않는다 (E)

V1  V2  V3 gender
C   7  35  88    NaN
A   3  25  45      여
B   5  56  76      남
F   2  34  79      남
D   2  34  79      남

In [92]:
Exam=DataFrame(arr.T, columns=["V1", "V2", "V3"], index=["A", "B", "C", "F"])
gender=Series(["남","여","남","남"], index=["D","A","E","B"])

Exam["gender"]=gender 
Exam=Exam.reindex(["C","A","B","F","E"], method="ffill")
Exam # 앞꺼 참고해서 채워주는건 테이블 기준으로 ; 따라서 C의 값이 A에도 채워짐

V1  V2  V3 gender
C   7  35  88    NaN
A   3  25  45      여
B   5  56  76      남
F   2  34  79    NaN
E   7  35  88    NaN

In [98]:
df=DataFrame(arr.T, columns=["V1", "V2", "V3"], index=["A", "B", "C", "D"])
print(df)
df2=df.drop(["A"])
df2

   V1  V2  V3
A   3  25  45
B   5  56  76
C   7  35  88
D   2  34  79


V1  V2  V3
B   5  56  76
C   7  35  88
D   2  34  79

## 색인하기, 선택하기, 거르기

In [99]:
Ex=Series([3,5,2,6])
Ex.reindex([2,0,3,5,1],method="ffill")
print(Ex, "\n\n\n", Ex[[1,0,2]]) # 원래 있던 값들은 안 바뀐다

0    3
1    5
2    2
3    6
dtype: int64 


 1    5
0    3
2    2
dtype: int64


#### 논리값을 이용한 선택

In [102]:
Ex=Series([3,5,2,6])
Ex=Ex.reindex([2,0,3,5,1],method="ffill")
b_data=(Ex>=3.5)
print(b_data)
print(Ex, "\n\n\n", Ex[b_data]) 

2    False
0    False
3     True
5     True
1     True
dtype: bool
2    2
0    3
3    6
5    6
1    5
dtype: int64 


 3    6
5    6
1    5
dtype: int64


In [106]:
obj=Series([2.5,6.4,7.8,6.5], index=["kim","cho","bae", "lee"])
obj[obj>=6]=float("NaN") # 6 이상의 자료를 NaN
print(obj)

kim    2.5
cho    NaN
bae    NaN
lee    NaN
dtype: float64


### 랜덤으로 변수들 만들기

In [113]:
### x=np.random.rand(100)
gender=np.where(x>0.5,"M","F")
gender

array(['M', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F', 'M', 'F', 'M',
       'F', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'M', 'F', 'F', 'M',
       'M', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F',
       'M', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'F', 'F', 'F', 'F', 'M',
       'F', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'F',
       'F', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'M',
       'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'F',
       'M', 'F', 'M', 'F', 'F', 'F', 'M', 'F', 'M'], dtype='<U1')

In [123]:
height=np.rint(np.random.normal(loc=175,scale=6,size=100))
height

array([177., 176., 193., 181., 173., 178., 176., 173., 182., 178., 178.,
       173., 169., 176., 172., 177., 180., 167., 168., 167., 181., 177.,
       171., 172., 180., 185., 175., 177., 177., 173., 178., 174., 172.,
       171., 181., 176., 169., 177., 170., 178., 182., 177., 163., 174.,
       178., 179., 162., 173., 171., 182., 178., 171., 183., 179., 171.,
       181., 168., 178., 170., 168., 176., 179., 172., 170., 170., 171.,
       174., 175., 179., 180., 173., 167., 173., 184., 176., 177., 184.,
       178., 170., 169., 166., 182., 166., 173., 186., 179., 171., 168.,
       173., 176., 182., 185., 168., 175., 187., 164., 178., 181., 182.,
       186.])

In [124]:
weight=np.rint(np.random.normal(loc=68,scale=3,size=100))
weight

array([70., 66., 68., 73., 72., 67., 69., 68., 69., 68., 67., 65., 69.,
       67., 72., 68., 71., 66., 62., 71., 72., 64., 66., 65., 64., 70.,
       72., 70., 68., 61., 64., 67., 64., 66., 71., 70., 68., 67., 68.,
       67., 68., 69., 68., 75., 68., 70., 67., 70., 70., 69., 63., 73.,
       66., 65., 65., 71., 73., 66., 68., 67., 69., 65., 68., 65., 67.,
       69., 67., 61., 72., 67., 68., 68., 65., 66., 68., 67., 70., 69.,
       67., 67., 68., 72., 68., 71., 65., 67., 73., 66., 72., 71., 64.,
       65., 70., 76., 67., 64., 66., 69., 75., 65.])

In [155]:
DF=DataFrame({"Gender":gender, "Height":height, "Weight":weight})
#DataFrame(np.array([gender,height,weight]).T, columns=["Gender", "Height", "Weight"])
DF

Gender  Height  Weight
0       M   177.0    70.0
1       F   176.0    66.0
2       M   193.0    68.0
3       F   181.0    73.0
4       F   173.0    72.0
5       F   178.0    67.0
6       M   176.0    69.0
7       M   173.0    68.0
8       M   182.0    69.0
9       F   178.0    68.0
10      M   178.0    67.0
11      F   173.0    65.0
12      M   169.0    69.0
13      F   176.0    67.0
14      F   172.0    72.0
15      M   177.0    68.0
16      F   180.0    71.0
17      F   167.0    66.0
18      F   168.0    62.0
19      M   167.0    71.0
20      M   181.0    72.0
21      F   177.0    64.0
22      M   171.0    66.0
23      F   172.0    65.0
24      F   180.0    64.0
25      M   185.0    70.0
26      M   175.0    72.0
27      F   177.0    70.0
28      M   177.0    68.0
29      F   173.0    61.0
..    ...     ...     ...
70      M   173.0    68.0
71      M   167.0    68.0
72      F   173.0    65.0
73      F   184.0    66.0
74      F   176.0    68.0
75      M   177.0    67.0
76      M   184.0    70.0
77      M   178.0    69.0
78      F   170.0    67.0
79      F   169.0    67.0
80      F   166.0    68.0
81      F   182.0    72.0
82      M   166.0    68.0
83      F   173.0    71.0
84      M   186.0    65.0
85      F   179.0    67.0
86      M   171.0    73.0
87      M   168.0    66.0
88      F   173.0    72.0
89      F   176.0    71.0
90      F   182.0    64.0
91      M   185.0    65.0
92      F   168.0    70.0
93      M   175.0    76.0
94      F   187.0    67.0
95      F   164.0    64.0
96      F   178.0    66.0
97      M   181.0    69.0
98      F   182.0    75.0
99      M   186.0    65.0

[100 rows x 3 columns]

#### 자료 임의로 분할하기

In [156]:
np.random.seed(100)
rand_num=np.random.rand(100)
select=rand_num<0.9
select, np.sum(select)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False, False,  True,  True,  True,  True,  True,  True,
         True, False, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]), 91)

In [157]:
trainDF=DF[select]
trainDF # TRAIN DATA

Gender  Height  Weight
0       M   177.0    70.0
1       F   176.0    66.0
2       M   193.0    68.0
3       F   181.0    73.0
4       F   173.0    72.0
5       F   178.0    67.0
6       M   176.0    69.0
7       M   173.0    68.0
8       M   182.0    69.0
9       F   178.0    68.0
10      M   178.0    67.0
11      F   173.0    65.0
12      M   169.0    69.0
13      F   176.0    67.0
14      F   172.0    72.0
16      F   180.0    71.0
17      F   167.0    66.0
18      F   168.0    62.0
19      M   167.0    71.0
20      M   181.0    72.0
22      M   171.0    66.0
23      F   172.0    65.0
24      F   180.0    64.0
25      M   185.0    70.0
26      M   175.0    72.0
27      F   177.0    70.0
28      M   177.0    68.0
29      F   173.0    61.0
30      M   178.0    64.0
31      M   174.0    67.0
..    ...     ...     ...
67      F   175.0    61.0
68      F   179.0    72.0
69      F   180.0    67.0
70      M   173.0    68.0
71      M   167.0    68.0
72      F   173.0    65.0
75      M   177.0    67.0
76      M   184.0    70.0
77      M   178.0    69.0
78      F   170.0    67.0
79      F   169.0    67.0
80      F   166.0    68.0
81      F   182.0    72.0
82      M   166.0    68.0
84      M   186.0    65.0
85      F   179.0    67.0
86      M   171.0    73.0
87      M   168.0    66.0
88      F   173.0    72.0
89      F   176.0    71.0
90      F   182.0    64.0
91      M   185.0    65.0
92      F   168.0    70.0
93      M   175.0    76.0
94      F   187.0    67.0
95      F   164.0    64.0
96      F   178.0    66.0
97      M   181.0    69.0
98      F   182.0    75.0
99      M   186.0    65.0

[91 rows x 3 columns]

In [158]:
testDF=DF[~select]
testDF # TEST DATA

Gender  Height  Weight
15      M   177.0    68.0
21      F   177.0    64.0
36      F   169.0    68.0
50      F   178.0    63.0
64      F   170.0    67.0
65      F   171.0    69.0
73      F   184.0    66.0
74      F   176.0    68.0
83      F   173.0    71.0

In [159]:
male=DF[DF.Gender=="M"]; female=DF[DF.Gender=="F"]
print("{0},\t\t\t,{1}" .format(male, female))

   Gender  Height  Weight
0       M   177.0    70.0
2       M   193.0    68.0
6       M   176.0    69.0
7       M   173.0    68.0
8       M   182.0    69.0
10      M   178.0    67.0
12      M   169.0    69.0
15      M   177.0    68.0
19      M   167.0    71.0
20      M   181.0    72.0
22      M   171.0    66.0
25      M   185.0    70.0
26      M   175.0    72.0
28      M   177.0    68.0
30      M   178.0    64.0
31      M   174.0    67.0
32      M   172.0    64.0
33      M   171.0    66.0
35      M   176.0    70.0
37      M   177.0    67.0
39      M   178.0    67.0
42      M   163.0    68.0
43      M   174.0    75.0
44      M   178.0    68.0
45      M   179.0    70.0
51      M   171.0    73.0
54      M   171.0    65.0
58      M   170.0    68.0
61      M   179.0    65.0
62      M   172.0    68.0
66      M   174.0    67.0
70      M   173.0    68.0
71      M   167.0    68.0
75      M   177.0    67.0
76      M   184.0    70.0
77      M   178.0    69.0
82      M   166.0    68.0
84      M   

In [165]:
NewData=DF[(DF.Gender=="M")&(DF.Height>=180)]
NewData

Gender  Height  Weight
2       M   193.0    68.0
8       M   182.0    69.0
20      M   181.0    72.0
25      M   185.0    70.0
76      M   184.0    70.0
84      M   186.0    65.0
91      M   185.0    65.0
97      M   181.0    69.0
99      M   186.0    65.0

## 산술 연산과 데이터 정렬: 같은 인덱스를 기준으로 연산

In [174]:
Ex1=Series(np.random.binomial(n=100,p=0.6, size=6), index=["A","B","D","E","F","H"])
Ex2=Series(np.random.binomial(n=50,p=0.4, size=6), index=["B","C","A","D","F","E"])
print(Ex1, "\n", Ex2, "\n", Ex1+Ex2) 

A    57
B    68
D    61
E    53
F    56
H    63
dtype: int32 
 B    21
C    23
A    26
D    22
F    20
E    20
dtype: int32 
 A    83.0
B    89.0
C     NaN
D    83.0
E    73.0
F    76.0
H     NaN
dtype: float64


### 메소드로 해도 똑같다 (변수이름.add(더할 변수))

In [177]:
print(Ex1, "\n", Ex2, "\n", Ex1.add(Ex2) )

A    57
B    68
D    61
E    53
F    56
H    63
dtype: int32 
 B    21
C    23
A    26
D    22
F    20
E    20
dtype: int32 
 A    83.0
B    89.0
C     NaN
D    83.0
E    73.0
F    76.0
H     NaN
dtype: float64


### 결측값 어떻게 처리할건지 지정해줄수있다 (fill)

In [179]:
print(Ex1, "\n", Ex2, "\n", Ex1.add(Ex2, fill_value=0) )

A    57
B    68
D    61
E    53
F    56
H    63
dtype: int32 
 B    21
C    23
A    26
D    22
F    20
E    20
dtype: int32 
 A    83.0
B    89.0
C    23.0
D    83.0
E    73.0
F    76.0
H    63.0
dtype: float64


### DataFrame과 Series의 연산

In [182]:
Ex1=Series([3,5,1],index=["att","hw","etc"])
Ex2=Series([3,5,1],index=["st1","st4","st2"])
DF=DataFrame({"att":[5,7,8,6], "hw":[8,7,9,6], "mid":[36,32,25,28], "fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(DF, "\n", Ex1, "\n", DF+Ex1)

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
 att    3
hw     5
etc    1
dtype: int64 
       att  etc  fin    hw  mid
st1   8.0  NaN  NaN  13.0  NaN
st2  10.0  NaN  NaN  12.0  NaN
st3  11.0  NaN  NaN  14.0  NaN
st4   9.0  NaN  NaN  11.0  NaN


### 마찬가지로, method를 이용해서 연산해도 된다.

In [184]:
print(DF, "\n", Ex1, "\n", DF.add(Ex1,axis=0))

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
 att    3
hw     5
etc    1
dtype: int64 
      att  hw  mid  fin
att  NaN NaN  NaN  NaN
etc  NaN NaN  NaN  NaN
hw   NaN NaN  NaN  NaN
st1  NaN NaN  NaN  NaN
st2  NaN NaN  NaN  NaN
st3  NaN NaN  NaN  NaN
st4  NaN NaN  NaN  NaN


In [185]:
print(DF, "\n", Ex1, "\n", DF.add(Ex2,axis=0))

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
 att    3
hw     5
etc    1
dtype: int64 
       att    hw   mid   fin
st1   8.0  11.0  39.0  35.0
st2   8.0   8.0  33.0  28.0
st3   NaN   NaN   NaN   NaN
st4  11.0  11.0  33.0  25.0


## 함수의 적용과 맵핑

In [187]:
Ex1=Series([3,5,1],index=["att","hw","etc"])
Ex2=Series([4,2,10,3],index=["st1","st4","st2", "st3"])
DF=DataFrame({"att":[5,7,8,6], "hw":[8,7,9,6], "mid":[36,32,25,28], "fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(np.minimum(Ex1,Ex2))

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

### numpy함수는 인덱스를 전혀 고려하지 않고 순서만 고려 (Ex1, Ex2  인덱스 모두 다름)

In [188]:
Ex1=Series([3,5,1],index=["att","hw","etc"])
Ex2=Series([4,2,10],index=["st1","st4","st2"])
DF=DataFrame({"att":[5,7,8,6], "hw":[8,7,9,6], "mid":[36,32,25,28], "fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(np.minimum(Ex1,Ex2))

att    3
hw     2
etc    1
dtype: int64


### apply() 안에 쓸 함수 넣음 (개별 원소별로 계산하는거 말고 전체적으로 계산하는것, e.g. 평균, 표준편차)

In [190]:
 print(DF, "\n", DF.apply(np.sum))

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
 att     26
hw      30
mid    121
fin     98
dtype: int64


In [192]:
 print(DF, "\n", DF.apply(np.sum,axis=1)) # 각 행에 대한 합계

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
 st1    81
st2    73
st3    61
st4    60
dtype: int64


### 사용자 지정 함수를 apply()에 넣고 각 열을 순차적으로 함수 돌리기 -> 데이터프레임으로 출력

In [195]:
def f(x):
    return(Series([x.min(), x.max(), x.max()-x.min()], index=["최소값", "최대값", "범위"]))
print(DF, "\n", DF.apply(f,axis=1))
DF.apply(f)

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
      최소값  최대값  범위
st1    5   36  31
st2    7   32  25
st3    8   25  17
st4    6   28  22


att  hw  mid  fin
최소값    5   6   25   19
최대값    8   9   36   32
범위     3   3   11   13

In [196]:
def f(x):
    return(Series([x.min(), x.max(), x.max()-x.min()], index=["최소값", "최대값", "범위"]))
print(DF, "\n", DF.apply(f))

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
      att  hw  mid  fin
최소값    5   6   25   19
최대값    8   9   36   32
범위     3   3   11   13


#### DF.applymap(np.exp) = np.exp(DF) -> 이렇게 내장된 함수들은 굳이 apply()함수를 사용하지 않아도 된다; 원소별 계산을 원하면 그냥 내장된 함수를 써도 되고, 기존에 없는 설정이라면 apply함수를 씀

In [197]:
print(DF, "\n", DF.applymap(np.exp))

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
              att           hw           mid           fin
st1   148.413159  2980.957987  4.311232e+15  7.896296e+13
st2  1096.633158  1096.633158  7.896296e+13  5.320482e+11
st3  2980.957987  8103.083928  7.200490e+10  1.784823e+08
st4   403.428793   403.428793  1.446257e+12  4.851652e+08


In [198]:
np.exp(DF)

att           hw           mid           fin
st1   148.413159  2980.957987  4.311232e+15  7.896296e+13
st2  1096.633158  1096.633158  7.896296e+13  5.320482e+11
st3  2980.957987  8103.083928  7.200490e+10  1.784823e+08
st4   403.428793   403.428793  1.446257e+12  4.851652e+08

## 정렬과 순위

In [200]:
Ex1=Series([3,5,np.inf,7,5,np.nan,6,1],index=["a3", "a2", "a1", "a8","a6", "a4", "a7", "a5"])
DF=DataFrame({"att":[5,7,8,6], "hw":[8,7,9,6], "mid":[36,32,25,28], "fin":[32,27,19,20]},index=["st1","st2","st3","st4"])
print(Ex1, "\n", DF)

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 
      att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20


#### sort 디폴트는 오름차순 정렬

In [202]:
print(Ex1, "\n", Ex1.sort_index())

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 
 a1    inf
a2    5.0
a3    3.0
a4    NaN
a5    1.0
a6    5.0
a7    6.0
a8    7.0
dtype: float64


In [204]:
print(Ex1, "\n", Ex1.sort_index(ascending=False), "\n", Ex1.sort_values(ascending=False))

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 
 a8    7.0
a7    6.0
a6    5.0
a5    1.0
a4    NaN
a3    3.0
a2    5.0
a1    inf
dtype: float64 
 a1    inf
a8    7.0
a7    6.0
a6    5.0
a2    5.0
a3    3.0
a5    1.0
a4    NaN
dtype: float64


In [206]:
print(Ex1, "\n", Ex1.rank(method="first")) # 얘는 동률이면 먼저 나온애를 

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 
 a3    2.0
a2    3.0
a1    7.0
a8    6.0
a6    4.0
a4    NaN
a7    5.0
a5    1.0
dtype: float64


In [207]:
print(Ex1, "\n", Ex1.rank()) # 얘는 두개가 동률이면 0.5씩 나눠갖는다

a3    3.0
a2    5.0
a1    inf
a8    7.0
a6    5.0
a4    NaN
a7    6.0
a5    1.0
dtype: float64 
 a3    2.0
a2    3.5
a1    7.0
a8    6.0
a6    3.5
a4    NaN
a7    5.0
a5    1.0
dtype: float64


In [208]:
print(DF, "\n", DF.rank(axis=1,method="average"))  # 행 별로 랭크내고 싶을 때

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20 
      att   hw  mid  fin
st1  1.0  2.0  4.0  3.0
st2  1.5  1.5  4.0  3.0
st3  1.0  2.0  4.0  3.0
st4  1.5  1.5  4.0  3.0


## 중복 색인

In [210]:
print(DF.index.is_unique)

True


## 기술통계 계산과 요약

In [214]:
Ex1=Series([3,5,np.inf,7,5,np.nan,6,1],index=["a3", "a2", "a1", "a8","a6", "a4", "a7", "a5"])
Ex1.mean() # Inf가 포함되어 있어서

inf

In [212]:
Ex1.mean(skipna=False) # nan을 무시 못하니 계산을 못함

nan

In [215]:
Ex1.mean(skipna=True) # 디폴트가 skip NaN

inf

In [216]:
print(DF)

     att  hw  mid  fin
st1    5   8   36   32
st2    7   7   32   27
st3    8   9   25   19
st4    6   6   28   20


In [217]:
DF.mean()

att     6.50
hw      7.50
mid    30.25
fin    24.50
dtype: float64

In [218]:
DF.cumsum(skipna=False) # -> false로 되어있으면, nan 나온 시점 이후로 모두 NaN

att  hw  mid  fin
st1    5   8   36   32
st2   12  15   68   59
st3   20  24   93   78
st4   26  30  121   98

In [220]:
DF.describe() # 기술통계

att        hw        mid        fin
count  4.000000  4.000000   4.000000   4.000000
mean   6.500000  7.500000  30.250000  24.500000
std    1.290994  1.290994   4.787136   6.137318
min    5.000000  6.000000  25.000000  19.000000
25%    5.750000  6.750000  27.250000  19.750000
50%    6.500000  7.500000  30.000000  23.500000
75%    7.250000  8.250000  33.000000  28.250000
max    8.000000  9.000000  36.000000  32.000000

In [225]:
DF.att.describe() # 특정 렬의 기술통계도 제공

count    4.000000
mean     6.500000
std      1.290994
min      5.000000
25%      5.750000
50%      6.500000
75%      7.250000
max      8.000000
Name: att, dtype: float64